[workspace]
resolver = "2"
members = ["crates/core", "crates/cli", "crates/gui"]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "GPL-2.0-or-later"

# hashing 100s of MB in an unoptimised debug build is painfully slow
[profile.dev.package.sha3]
opt-level = 3
[profile.dev.package.sha2]
opt-level = 3
