# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

CRATES=""

RUST_MIN_VER="1.92"

# The sources were written for this Zig (container-format parsers, built by crates/core/build.rs).
ZIG_SLOT="0.16"

inherit cargo desktop optfeature xdg zig-utils git-r3

DESCRIPTION="Windows-style app installer: deb, rpm, snap, AppImage, Flatpak, exe, archives"
HOMEPAGE="https://github.com/tarilka0gg/ustan"
EGIT_REPO_URI="https://github.com/tarilka0gg/ustan.git"
# to build a local checkout: EGIT_OVERRIDE_REPO_TARILKA0GG_USTAN=file:///path/to/ustan

LICENSE="GPL-2+"
# Dependent crate licenses (generated by packaging/gentoo/gen-ebuild-data.py). rust-lzo is GPL-2 only,
# so the installed binaries are a GPL-2 combined work. liblzma-sys builds xz from source (0BSD),
# which backhand forces; bzip2 is a pure-Rust crate, zstd is linked from the system.
LICENSE+=" 0BSD Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD BZIP2 Boost-1.0 CDLA-Permissive-2.0 GPL-2 ISC LGPL-2.1+ MIT Unicode-3.0 Unlicense ZLIB"
SLOT="0"
IUSE="+gui flatpak wine"

# bubblewrap: deb/rpm/Arch programs run with the package overlaid on /usr, snaps run in a sandbox
RDEPEND="
	app-arch/zstd:=
	sys-apps/bubblewrap
	x11-misc/xdg-utils
	gui? (
		>=gui-libs/gtk-4.10:4
		>=gui-libs/libadwaita-1.6:1
	)
	flatpak? ( sys-apps/flatpak )
	wine? ( virtual/wine )
"
DEPEND="
	app-arch/zstd:=
	gui? (
		>=gui-libs/gtk-4.10:4
		>=gui-libs/libadwaita-1.6:1
	)
"
BDEPEND="virtual/pkgconfig"

# Zig builds a static library that does not honour CFLAGS/LDFLAGS; the Rust side does
QA_FLAGS_IGNORED="usr/bin/ustan usr/bin/ustan-gui"

src_unpack() {
	git-r3_src_unpack
	cargo_live_src_unpack
}

pkg_setup() {
	rust_pkg_setup
}

src_configure() {
	zig-utils_find_installation
	export ZIG="${ZIG_EXE}"          # crates/core/build.rs
	export ZSTD_SYS_USE_PKG_CONFIG=1 # system libzstd instead of the bundled copy
	cargo_src_configure
}

src_compile() {
	cargo_src_compile -p ustan $(usev gui '-p ustan-gui')
}

src_test() {
	cargo_src_test -p ustan-core -p ustan --  # trailing "--": cargo.eclass mis-splits args without it
	( cd zig && ezig build test ) || die "zig tests failed"
}

src_install() {
	cargo_src_install --path crates/cli
	if use gui; then
		cargo_src_install --path crates/gui
		domenu packaging/io.github.tarilka0gg.Ustan.desktop
	fi
	insinto /usr/share/metainfo
	doins packaging/io.github.tarilka0gg.Ustan.metainfo.xml
	insinto /usr/share/icons/hicolor/scalable/apps
	doins packaging/icons/ustan.svg
	einstalldocs
}

pkg_postinst() {
	xdg_pkg_postinst
	optfeature "update notifications (ustan watch)" x11-libs/libnotify
	optfeature ".jar applications" virtual/jre
	optfeature "installing from Flathub (flatpak: references)" sys-apps/flatpak
	if use gui; then
		elog "ustan-gui registers itself as the handler of its file types on its first start"
		elog "(undo with: ustan unregister). Or run: ustan register"
	fi
}

pkg_postrm() {
	xdg_pkg_postrm
}
