[package]
name = "ustan-core"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.8"
thiserror = "1"
tar = "0.4"
flate2 = "1"
lzma-rs = "0.3"
ruzstd = "0.8"
backhand = "0.25.5"
ureq = { version = "2", features = ["json"] }
sha2 = "0.10"
image = { version = "0.25", default-features = false, features = ["ico", "png"] }
serde_json = "1"
