//! `.snap` packages: a squashfs with `meta/snap.yaml`. We unpack without snapd and generate
//! launchers that set up the `SNAP*` environment. Snaps that rely on other snaps (a `base`
//! or content runtimes such as gnome-*) can only run if they bundle what they need.
use super::tree::{dest, install_tree, remove_existing, safe_rel, Spec};
use super::{slug, Backend, Icon, Info, Opts};
use crate::{dirs::Dirs, manifest::Manifest, Error, Result};
use backhand::{FilesystemReader, InnerNode};
use std::io::{BufReader, Read};
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

pub struct Snap;

type Fs = FilesystemReader<'static>;

fn open(path: &Path) -> Result<Fs> {
    FilesystemReader::from_reader(BufReader::new(std::fs::File::open(path)?)).map_err(|e| Error::Format(format!("squashfs: {e}")))
}

fn read(fs: &Fs, rel: &str) -> Option<Vec<u8>> {
    let want = Path::new("/").join(rel);
    let n = fs.files().find(|n| n.fullpath == want)?;
    match &n.inner {
        InnerNode::File(f) => {
            let mut v = Vec::new();
            fs.file(f).reader().read_to_end(&mut v).ok()?;
            Some(v)
        }
        _ => None,
    }
}

#[derive(Debug, Clone)]
struct App {
    name: String,
    command: String,
    chain: Vec<String>,
    daemon: bool,
}

#[derive(Debug)]
struct Meta {
    name: String,
    version: String,
    apps: Vec<App>,
    /// Other snaps this one expects to be connected (content interface default-providers).
    providers: Vec<String>,
}

fn parse_yaml(text: &str) -> Result<Meta> {
    let y: serde_yaml::Value = serde_yaml::from_str(text).map_err(|e| Error::Format(format!("snap.yaml: {e}")))?;
    let s = |k: &str| y.get(k).and_then(|v| v.as_str().map(str::to_string).or_else(|| v.as_f64().map(|f| f.to_string())));
    let name = s("name").ok_or_else(|| Error::Format("snap.yaml has no name".into()))?;
    let mut apps = Vec::new();
    if let Some(m) = y.get("apps").and_then(|a| a.as_mapping()) {
        for (k, v) in m {
            let (Some(an), Some(cmd)) = (k.as_str(), v.get("command").and_then(|c| c.as_str())) else { continue };
            let chain = v
                .get("command-chain")
                .and_then(|c| c.as_sequence())
                .map(|c| c.iter().filter_map(|x| x.as_str().map(str::to_string)).collect())
                .unwrap_or_default();
            apps.push(App { name: an.to_string(), command: cmd.to_string(), chain, daemon: v.get("daemon").is_some() });
        }
    }
    let mut providers: Vec<String> = y
        .get("plugs")
        .and_then(|p| p.as_mapping())
        .map(|m| m.values().filter_map(|v| v.get("default-provider").and_then(|d| d.as_str())).map(|d| d.split(':').next().unwrap_or(d).to_string()).collect())
        .unwrap_or_default();
    providers.sort();
    providers.dedup();
    Ok(Meta { name, version: s("version").unwrap_or_default(), apps, providers })
}

fn meta(fs: &Fs) -> Result<Meta> {
    let text = read(fs, "meta/snap.yaml").ok_or_else(|| Error::Format("no meta/snap.yaml: not a snap".into()))?;
    parse_yaml(&String::from_utf8_lossy(&text))
}

/// Make a command from snap.yaml runnable from our wrapper: relative paths live under $SNAP.
fn absolutize(c: &str) -> String {
    match c.split_whitespace().next() {
        Some(first) if !first.starts_with('/') && !first.starts_with('$') => format!("\"$SNAP\"/{c}"),
        _ => c.to_string(),
    }
}

fn wrapper(root: &Path, m: &Meta, app: &App) -> String {
    let cmd = app.chain.iter().map(|c| absolutize(c)).chain([absolutize(&app.command)]).collect::<Vec<_>>().join(" ");
    let n = &m.name;
    format!(
        r#"#!/bin/sh
# generated by ustan
SNAP="{root}"
export SNAP SNAP_NAME="{n}" SNAP_INSTANCE_NAME="{n}" SNAP_VERSION="{v}" SNAP_ARCH=amd64 SNAP_REVISION=x1
export SNAP_DATA="$HOME/snap/{n}/current" SNAP_COMMON="$HOME/snap/{n}/common"
export SNAP_USER_DATA="$HOME/snap/{n}/current" SNAP_USER_COMMON="$HOME/snap/{n}/common"
mkdir -p "$SNAP_USER_DATA" "$SNAP_USER_COMMON"
export LD_LIBRARY_PATH="$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu${{LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}}"
export PATH="$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin${{PATH:+:$PATH}}"
exec {cmd} "$@"
"#,
        root = root.display(),
        v = m.version,
    )
}

fn extract(fs: &Fs, root: &Path) -> Result<()> {
    let canon = root.canonicalize()?;
    for n in fs.files() {
        let Some(rel) = safe_rel(&n.fullpath.to_string_lossy()) else { continue };
        let mode = (n.header.permissions as u32) & 0o777;
        match &n.inner {
            InnerNode::Dir(_) => {
                let d = dest(root, &canon, &rel)?;
                std::fs::create_dir_all(&d)?;
                std::fs::set_permissions(&d, std::fs::Permissions::from_mode(mode | 0o700))?;
            }
            InnerNode::File(f) => {
                let d = dest(root, &canon, &rel)?;
                remove_existing(&d);
                let mut out = std::fs::File::create(&d)?;
                std::io::copy(&mut fs.file(f).reader(), &mut out)?;
                std::fs::set_permissions(&d, std::fs::Permissions::from_mode(mode | 0o200))?;
            }
            InnerNode::Symlink(l) => {
                let d = dest(root, &canon, &rel)?;
                remove_existing(&d);
                std::os::unix::fs::symlink(&l.link, &d)?;
            }
            _ => {}
        }
    }
    Ok(())
}

fn warning(m: &Meta) -> Option<String> {
    (!m.providers.is_empty())
        .then(|| format!("залежить від інших snap-ів ({}), яких без snapd немає: програма може не запуститися", m.providers.join(", ")))
}

fn icon_of(fs: &Fs) -> Option<Icon> {
    for (n, ext) in [("meta/gui/icon.png", "png"), ("meta/gui/icon.svg", "svg"), ("meta/gui/icon.xpm", "xpm")] {
        if let Some(bytes) = read(fs, n) {
            return Some(Icon { ext, bytes });
        }
    }
    // Themed icon: take the name from the snap's launcher and find the file in the image.
    let name = fs
        .files()
        .filter(|n| n.fullpath.starts_with("/meta/gui") && n.fullpath.extension().is_some_and(|e| e == "desktop"))
        .find_map(|n| {
            let rel = n.fullpath.strip_prefix("/").ok()?.to_string_lossy().into_owned();
            let text = String::from_utf8(read(fs, &rel)?).ok()?;
            text.lines().find_map(|l| l.strip_prefix("Icon=")).map(str::to_string)
        })?;
    // Themed names are dotted (org.gnome.Calculator): only strip real image extensions.
    let stem = [".svg", ".png", ".xpm"].iter().find_map(|e| name.strip_suffix(e)).unwrap_or(&name).to_string();
    let best = fs
        .files()
        .filter(|n| matches!(n.inner, InnerNode::File(_)))
        .filter(|n| n.fullpath.file_stem().is_some_and(|s| s.to_string_lossy() == stem))
        .filter(|n| n.fullpath.extension().is_some_and(|e| e == "svg" || e == "png"))
        .max_by_key(|n| {
            let p = n.fullpath.to_string_lossy();
            // svg wins; otherwise the largest size directory (e.g. 256x256)
            if p.ends_with(".svg") { u32::MAX } else { p.split('/').filter_map(|c| c.split('x').next()?.parse::<u32>().ok()).max().unwrap_or(0) }
        })?;
    let rel = best.fullpath.strip_prefix("/").ok()?.to_string_lossy().into_owned();
    let ext = if rel.ends_with(".svg") { "svg" } else { "png" };
    Some(Icon { ext, bytes: read(fs, &rel)? })
}

impl Backend for Snap {
    fn kind(&self) -> &'static str {
        "snap"
    }

    fn detect(&self, path: &Path) -> bool {
        path.extension().is_some_and(|e| e.eq_ignore_ascii_case("snap"))
    }

    fn inspect(&self, path: &Path) -> Result<Info> {
        let fs = open(path)?;
        let m = meta(&fs)?;
        let warning = warning(&m);
        Ok(Info { id: slug(&m.name), name: m.name, version: Some(m.version), kind: "snap", icon: icon_of(&fs), warning })
    }

    fn install(&self, path: &Path, dirs: &Dirs, opts: &Opts) -> Result<Manifest> {
        let fs = open(path)?;
        let m = meta(&fs)?;
        let spec = Spec { kind: "snap", id: slug(&m.name), name: m.name.clone(), version: Some(m.version.clone()), source: path };
        install_tree(
            spec,
            dirs,
            opts,
            |root| extract(&fs, root),
            |root, dirs, id, files| {
                // Only our own launchers: drop the generic ones install_tree made from usr/share/applications.
                for f in files.drain(1..) {
                    let _ = std::fs::remove_file(f);
                }
                let run = root.join(".ustan-run");
                std::fs::create_dir_all(&run)?;
                std::fs::create_dir_all(&dirs.apps)?;
                let bin = dirs.opt.parent().unwrap_or(&dirs.opt).join("bin");
                for app in m.apps.iter().filter(|a| !a.daemon) {
                    let w = run.join(&app.name);
                    std::fs::write(&w, wrapper(root, &m, app))?;
                    std::fs::set_permissions(&w, std::fs::Permissions::from_mode(0o755))?;

                    if let Ok(text) = std::fs::read_to_string(root.join("meta/gui").join(format!("{}.desktop", app.name))) {
                        // The snap's own launcher: swap its Exec for our wrapper and resolve ${SNAP} in Icon.
                        let mut out = String::new();
                        for l in text.lines() {
                            let l = l.replace("${SNAP}", &root.display().to_string());
                            match l.split_once('=') {
                                Some(("Icon", v)) if !v.starts_with('/') => match crate::desktop::find_icon_deep(root, v) {
                                    Some(p) => out.push_str(&format!("Icon={}\n", p.display())),
                                    None => {
                                        out.push_str(&l);
                                        out.push('\n');
                                    }
                                },
                                Some(("Exec", v)) => {
                                    let rest = v.split_once(char::is_whitespace).map_or("", |(_, r)| r);
                                    out.push_str(&format!("Exec=\"{}\" {rest}\n", w.display()));
                                }
                                _ => {
                                    out.push_str(&l);
                                    out.push('\n');
                                }
                            }
                        }
                        let dst = dirs.apps.join(format!("ustan-{id}-{}.desktop", app.name));
                        std::fs::write(&dst, out)?;
                        files.push(dst);
                    } else {
                        // A command-line app: expose it in PATH under the usual snap name.
                        std::fs::create_dir_all(&bin)?;
                        let name = if app.name == m.name { app.name.clone() } else { format!("{}.{}", m.name, app.name) };
                        let link = bin.join(name);
                        if std::fs::symlink_metadata(&link).is_err() {
                            std::os::unix::fs::symlink(&w, &link)?;
                            files.push(link);
                        }
                    }
                }
                Ok(())
            },
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_snap_yaml() {
        let y = "name: demo\nversion: '1.5'\nbase: core22\napps:\n  demo:\n    command: bin/demo --x\n    command-chain: [snap/command-chain/launch]\n  svc:\n    command: bin/svc\n    daemon: simple\n";
        let m = parse_yaml(y).unwrap();
        assert_eq!((m.name.as_str(), m.version.as_str()), ("demo", "1.5"));
        assert_eq!(m.apps.len(), 2);
        assert!(m.apps[1].daemon);
        assert_eq!(m.apps[0].chain, vec!["snap/command-chain/launch".to_string()]);
    }

    #[test]
    fn commands_are_rooted_in_snap() {
        assert_eq!(absolutize("bin/hello"), "\"$SNAP\"/bin/hello");
        assert_eq!(absolutize("$SNAP/bin/x"), "$SNAP/bin/x");
        assert_eq!(absolutize("/usr/bin/env a"), "/usr/bin/env a");
    }
}
